<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        body { font-family: sans-serif; font-size: 14px; color: #333; }
        .receipt-box { border: 1px solid #333; padding: 20px; position: relative; }
        .header { text-align: center; border-bottom: 2px solid #1e3a8a; padding-bottom: 10px; margin-bottom: 20px; }
        .header h1 { margin: 0; color: #1e3a8a; font-size: 20px; text-transform: uppercase; }
        .header p { margin: 5px 0 0; font-size: 12px; color: #666; }
        .table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        .table td { padding: 8px 0; border-bottom: 1px dashed #eee; }
        .label { font-weight: bold; width: 30%; color: #1e3a8a; }
        .amount-row { background: #f9f9f9; margin-top: 20px; padding: 15px; text-align: right; border-left: 4px solid #1e3a8a; }
        .amount-row h3 { margin: 0; color: #1e3a8a; font-size: 24px; }
        .footer { margin-top: 40px; font-size: 10px; color: #888; }
        .signature-box { margin-top: 40px; text-align: right; }
        .signature-line { border-top: 1px solid #333; display: inline-block; width: 150px; margin-top: 40px; text-align: center; font-weight: bold; }
        .watermark { position: absolute; transform: rotate(-45deg); opacity: 0.05; font-size: 60px; font-weight: bold; top: 40%; left: 10%; width: 100%; text-align: center; }
    </style>
</head>
<body>
    <div class="receipt-box">
        <div class="watermark">OFFICIAL RECEIPT</div>
        
        <div class="header">
            <h1>Educational Ministerial Officers Association</h1>
            <p>Uttarakhand</p>
            <p><strong>Official Contribution Receipt</strong></p>
        </div>

        <table class="table">
            <tr>
                <td class="label">Receipt No:</td>
                <td>{{ $anshandan->receipt_no }}</td>
                <td class="label" style="text-align: right;">Date:</td>
                <td style="text-align: right;">{{ \Carbon\Carbon::parse($anshandan->payment_date)->format('d M, Y') }}</td>
            </tr>
        </table>

        <table class="table" style="margin-top: 20px;">
            <tr>
                <td class="label">Received From:</td>
                <td>{{ $anshandan->member_name }}</td>
            </tr>
            @if($anshandan->user_id)
            <tr>
                <td class="label">Employee Code:</td>
                <td>{{ $anshandan->user->employee_code ?? 'N/A' }}</td>
            </tr>
            @endif
            <tr>
                <td class="label">Contribution For:</td>
                <td>{{ $anshandan->month }}, {{ $anshandan->year }}</td>
            </tr>
            <tr>
                <td class="label">District:</td>
                <td>{{ $anshandan->district->name }}</td>
            </tr>
            @if($anshandan->block_id)
            <tr>
                <td class="label">Block:</td>
                <td>{{ $anshandan->block->name }}</td>
            </tr>
            @endif
            <tr>
                <td class="label">Payment Method:</td>
                <td>{{ $anshandan->payment_method }} {{ $anshandan->transaction_id ? '(ID: '.$anshandan->transaction_id.')' : '' }}</td>
            </tr>
        </table>

        <div class="amount-row">
            <span style="font-size: 12px; color: #666;">Total Amount Received</span><br>
            <h3>₹{{ number_format($anshandan->amount, 2) }}</h3>
        </div>

        <div class="signature-box">
            <div class="signature-line">
                Authorized Signatory
            </div>
        </div>

        <div class="footer">
            <p>This is a computer-generated receipt and does not require a physical signature.</p>
            <p>Generated on: {{ now()->format('d M, Y h:i A') }} | Generated by: {{ $anshandan->creator->name }}</p>
        </div>
    </div>
</body>
</html>
